name = "GeoLearning"
uuid = "90c4468e-a93e-43b4-8fb5-87d804bc629f"
authors = ["Júlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.1.6"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Distributions = "0.24, 0.25"
GeoStatsBase = "0.21, 0.22"
MLJModelInterface = "0.4, 1.0"
Meshes = "0.16, 0.17"
TableOperations = "1.0"
Tables = "1.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
